// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user_duration_event.proto

package com.zhaolion.flink.demo.proto.event;

public interface UserDurationEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:event.UserDurationEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>int64 event_at_ns = 2;</code>
   * @return The eventAtNs.
   */
  long getEventAtNs();

  /**
   * <code>int32 duration_sec = 3;</code>
   * @return The durationSec.
   */
  int getDurationSec();

  /**
   * <code>uint64 user_id = 4;</code>
   * @return The userId.
   */
  long getUserId();
}
