// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user_duration_event.proto

package com.zhaolion.flink_clickhouse_stack.event;

public final class UserDurationEventProto {
  private UserDurationEventProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_event_UserDurationEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_event_UserDurationEvent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031user_duration_event.proto\022\005event\"[\n\021Us" +
      "erDurationEvent\022\n\n\002id\030\001 \001(\t\022\023\n\013event_at_" +
      "ns\030\002 \001(\003\022\024\n\014duration_sec\030\003 \001(\005\022\017\n\007user_i" +
      "d\030\004 \001(\004Bw\n)com.zhaolion.flink_clickhouse" +
      "_stack.eventB\026UserDurationEventProtoP\001Z0" +
      "github.com/zhaolion/flink-clickhouse-sta" +
      "ck/eventb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_event_UserDurationEvent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_event_UserDurationEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_event_UserDurationEvent_descriptor,
        new java.lang.String[] { "Id", "EventAtNs", "DurationSec", "UserId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
